blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/AlexWabita/equalizer-apo-profiles/discussions
    about: Ask questions or discuss ideas with the community
  - name: Equalizer APO Documentation
    url: https://sourceforge.net/p/equalizerapo/wiki/Documentation/
    about: Official Equalizer APO documentation and help
